#!/bin/sh
set -eu
VERSION="1.0.7"
AUTHOR="mazunki"

version() {
	printf "v${VERSION:?} by ${AUTHOR:?}\n"
	return
}

usage() {
	printf "xkcd <number> || xkcd xkcd://<number>\n"
	return
}

printerr() {
	printf "[error] %s: %s\n" "$0" "$1" >&2
	exit 1
}

test $# -eq 1 || { usage; exit 1; }

set -- "${1#xkcd://}"

case "$1" in
	'') usage ;;
	-h|--help) usage; exit ;;
	-v|--version) version; exit ;;
	*[!0-9]*) printerr "Invalid parameter: $1" ;;
esac

exec xdg-open https://xkcd.com/"$1"

