#!/bin/sh
set -eu
VERSION="1.1.4"
AUTHOR="mazunki"
ALIAS_FILE="/usr/share/xkcd/aliases"  # TODO: dynamic pathing

version() {
	printf "v${VERSION:?} by ${AUTHOR:?}\n"
	return
}

usage() {
	printf "xkcd <number|alias> || xkcd xkcd://<number|alias>\n"
	return
}

printerr() {
	printf "[error] %s: %s\n" "$0" "$1" >&2
	exit 1
}

resolve() {
	if test -f "${ALIAS_FILE}"; then
		grep "^${1}:" "${ALIAS_FILE}" | cut -d':' -f2
	else
		printerr "no alias file"
	fi
}

test $# -eq 1 || { usage; exit 1; }

set -- "${1#xkcd://}"

case "$1" in
	'') usage ;;
	-h|--help) usage; exit ;;
	-v|--version) version; exit ;;
	*[!0-9]*)
		resolved="$(resolve "$1")"
		test -n "${resolved}" || {
			printerr "invalid parameter or unknown alias: $1"
		}

		set -- "${resolved}"
		;;
esac

exec xdg-open https://xkcd.com/"$1"

